version: '3.8'

services:
  gateway-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gateway_db

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: